### ISSUE TITLE
Package in Gentoo / needed by gentoolkit test suite

### ISSUE THREAD

**Issue by hartwork** [pkgcore/pkgdist#1]
Hi!

The current test suite of gentoolkit [relies on `snakeoil.distutils_extensions.test`](https://gitweb.gentoo.org/proj/gentoolkit.git/tree/setup.py#n107) which seems to be moved here as `pkgdist.test` now. It would be cool to get that test suite back to live so gentoolkit can be developed with confidence in its code.
Are there plans on packaging pkgdist for Gentoo? I don't see a build system currently. If I were to package it myself, would I just copy `pkgdist.py` into the right places? Can you add a Git tag for a release?

Thanks and best, Sebastian

**Comment by hartwork** [comment]
@radhermit what do you think?

**Comment by radhermit** [comment]
Originally pkgdist was at snakeoil.distutils_extensions as can be seen from gentoolkit's usage. It was debundled in order to fix bootstrapping issues with pip installs and will be remerged back into snakeoil once pip makes a release supporting PEPs 517 and 518 (https://github.com/pypa/pip/issues/4802).

That being said, it has diverged and been extended a lot since the last time someone probably used it for testing gentoolkit. I'd suggest updating gentoolkit to use setuptools directly instead of distutils and its support for specifying tests to run. The only reason I can see for using snakeoil's test support is if you want the tests to run against a built copy of the module without having any extra settings required.

**Comment by hartwork** [comment]
I see. Since the transition is not trivial, I made bug https://bugs.gentoo.org/644590 now in hope that someone can pick it up.

**Comment by radhermit** [comment]
Closing this since both snakeoil.dist.distutils_extensions exists and is used again thanks to pyproject.toml build-time deps for python packages, and gentoolkit dropped its snakeoil usage.
